import re

thesis_file = 'thesis/thesis.tex'
with open(thesis_file, 'r', encoding='utf-8') as f:
    content = f.read()

if '\\usepackage[normalem]{ulem}' not in content:
    content = content.replace('\\usepackage{microtype}  % přesnější typografie', '\\usepackage{microtype}  % přesnější typografie\n\\usepackage[normalem]{ulem} % pro přeškrtnutí textu')
    with open(thesis_file, 'w', encoding='utf-8') as f:
        f.write(content)

path = 'thesis/chapters/01_teorie.tex'
with open(path, 'r', encoding='utf-8') as f:
    c = f.read()

# 1. Systémová volání a přepnutí kontextu
c = c.replace('\\subsubsection{Systémová volání a přepnutí kontextu}', '\\subsubsection{\\sout{Systémová volání a přepnutí kontextu}}')
c = c.replace('Aplikace v uživatelském prostoru nemohou přímo přistupovat k hardwaru. Musí využívat tzv. \\textit{systémová volání} (syscalls) pro komunikaci s jádrem. Přechod mezi těmito prostory vyžaduje tzv. \\textit{přepnutí kontextu} (context switch), což je operace s nenulovou režií. V kontextu VPN řešení je toto kritické při zpracování síťového provozu – například protokoly běžící v uživatelském prostoru musí každý paket kopírovat mezi prostory přes virtuální síťové rozhraní (TUN/TAP), což může omezovat propustnost při vysokém zatížení. Naopak implementace přímo v prostoru jádra tuto režii minimalizují a umožňují efektivnější zpracování datových toků \\cite{wireguard_paper}.', '\\sout{Aplikace v uživatelském prostoru nemohou přímo přistupovat k hardwaru. Musí využívat tzv. \\textit{systémová volání} (syscalls) pro komunikaci s jádrem. Přechod mezi těmito prostory vyžaduje tzv. \\textit{přepnutí kontextu} (context switch), což je operace s nenulovou režií. V kontextu VPN řešení je toto kritické při zpracování síťového provozu – například protokoly běžící v uživatelském prostoru musí každý paket kopírovat mezi prostory přes virtuální síťové rozhraní (TUN/TAP), což může omezovat propustnost při vysokém zatížení. Naopak implementace přímo v prostoru jádra tuto režii minimalizují a umožňují efektivnější zpracování datových toků }\\cite{wireguard_paper}\\sout{.}')

# 2. Správa procesů a životní cyklus služeb
c = c.replace('\\subsection{Správa procesů a životní cyklus služeb}', '\\subsection{\\sout{Správa procesů a životní cyklus služeb}}')
c = c.replace('Proces je v Linuxu definován jako instance běžícího programu v paměti. Každý proces má svůj unikátní identifikátor (PID) a je spravován jádrem, které mu přiděluje procesorový čas a paměťové prostředky.', '\\sout{Proces je v Linuxu definován jako instance běžícího programu v paměti. Každý proces má svůj unikátní identifikátor (PID) a je spravován jádrem, které mu přiděluje procesorový čas a paměťové prostředky.}')
c = c.replace('\\subsubsection{Procesy a daemony}', '\\subsubsection{\\sout{Procesy a daemony}}')
c = c.replace('Vytváření nových procesů probíhá pomocí dvojice systémových volání \\texttt{fork()} a \\texttt{exec()}. Volání \\texttt{fork()} vytvoří identickou kopii rodičovského procesu, zatímco \\texttt{exec()} nahradí kód běžícího procesu novým programem. Tento mechanismus je základem pro spouštění všech aplikací v systému \\cite{ward_linux}.', '\\sout{Vytváření nových procesů probíhá pomocí dvojice systémových volání \\texttt{fork()} a \\texttt{exec()}. Volání \\texttt{fork()} vytvoří identickou kopii rodičovského procesu, zatímco \\texttt{exec()} nahradí kód běžícího procesu novým programem. Tento mechanismus je základem pro spouštění všech aplikací v systému }\\cite{ward_linux}\\sout{.}')
c = c.replace('Specifickou kategorií procesů jsou \\textit{daemony}. Jedná se o procesy, které běží na pozadí, nejsou přímo spojeny s žádným terminálem a typicky čekají na určité události nebo poskytují systémové služby. V moderní architektuře systémových nástrojů bývá logika implementována právě jako daemon, který udržuje stav (např. VPN spojení) nezávisle na tom, zda je uživatelské rozhraní zrovna spuštěno. Tento přístup zajišťuje persistenci spojení a umožňuje bezpečné provádění privilegovaných operací (např. manipulaci se síťovými rozhraními) pod identitou uživatele s dostatečnými právy, zatímco samotné rozhraní může běžet v kontextu běžného uživatele.', '\\sout{Specifickou kategorií procesů jsou \\textit{daemony}. Jedná se o procesy, které běží na pozadí, nejsou přímo spojeny s žádným terminálem a typicky čekají na určité události nebo poskytují systémové služby. V moderní architektuře systémových nástrojů bývá logika implementována právě jako daemon, který udržuje stav (např. VPN spojení) nezávisle na tom, zda je uživatelské rozhraní zrovna spuštěno. Tento přístup zajišťuje persistenci spojení a umožňuje bezpečné provádění privilegovaných operací (např. manipulaci se síťovými rozhraními) pod identitou uživatele s dostatečnými právy, zatímco samotné rozhraní může běžet v kontextu běžného uživatele.}')

# 3. Konfigurace síťového subsystému (Netlink)
c = c.replace('\\subsection{Konfigurace síťového subsystému (Netlink)}', '\\subsection{\\sout{Konfigurace síťového subsystému (Netlink)}}')
c = c.replace('Tradiční unixové nástroje (`ifconfig`) byly v Linuxu nahrazeny modernějším balíkem `iproute2`. Na pozadí těchto nástrojů stojí rozhraní \\textbf{Netlink}.', '\\sout{Tradiční unixové nástroje (`ifconfig`) byly v Linuxu nahrazeny modernějším balíkem `iproute2`. Na pozadí těchto nástrojů stojí rozhraní \\textbf{Netlink}.}')
c = c.replace('Netlink slouží jako komunikační sběrnice mezi jádrem a uživatelským prostorem \\cite{ward_linux}. Na rozdíl od `ioctl` volání, Netlink používá standardní mechanismus socketů pro předávání zpráv o konfiguraci sítě (např. přiřazení IP adresy, změna routovací tabulky).', '\\sout{Netlink slouží jako komunikační sběrnice mezi jádrem a uživatelským prostorem }\\cite{ward_linux}\\sout{. Na rozdíl od `ioctl` volání, Netlink používá standardní mechanismus socketů pro předávání zpráv o konfiguraci sítě (např. přiřazení IP adresy, změna routovací tabulky).}')

# 4. Behavior-Driven Development (BDD) a Gherkin
c = c.replace('\\subsection{Behavior-Driven Development (BDD) a Gherkin}', '\\subsection{\\sout{Behavior-Driven Development (BDD) a Gherkin}}')
c = c.replace('Vývoj řízený chováním (BDD – Behavior-Driven Development) je metodika, která rozšiřuje principy TDD o zaměření na uživatelský pohled a čitelnost scénářů pro netechnické členy týmu \\cite{bubble_tea_intro}. Specifikace jsou psány v přirozeném jazyce pomocí syntaxe \\textbf{Gherkin}.', '\\sout{Vývoj řízený chováním (BDD – Behavior-Driven Development) je metodika, která rozšiřuje principy TDD o zaměření na uživatelský pohled a čitelnost scénářů pro netechnické členy týmu }\\cite{bubble_tea_intro}\\sout{. Specifikace jsou psány v přirozeném jazyce pomocí syntaxe \\textbf{Gherkin}.}')
c = c.replace('Scénáře v Gherkinu využívají klíčová slova:', '\\sout{Scénáře v Gherkinu využívají klíčová slova:}')
c = c.replace('\\item \\textbf{Given (Za předpokladu):} Definice výchozího stavu systému.', '\\item \\sout{\\textbf{Given (Za předpokladu):} Definice výchozího stavu systému.}')
c = c.replace('\\item \\textbf{When (Když):} Akce, kterou uživatel nebo systém provede.', '\\item \\sout{\\textbf{When (Když):} Akce, kterou uživatel nebo systém provede.}')
c = c.replace('\\item \\textbf{Then (Pak):} Očekávaný výsledek operace.', '\\item \\sout{\\textbf{Then (Pak):} Očekávaný výsledek operace.}')
c = c.replace('Tento přístup umožňuje vytvořit tzv. „živou dokumentaci“, která je zároveň spustitelným testem. V rámci moderního inženýrství jsou Gherkin scénáře často využity pro precizní definici požadavků na rozhraní a chování systému, což zajišťuje, že implementace přesně odpovídá navržené specifikaci.', '\\sout{Tento přístup umožňuje vytvořit tzv. „živou dokumentaci“, která je zároveň spustitelným testem. V rámci moderního inženýrství jsou Gherkin scénáře často využity pro precizní definici požadavků na rozhraní a chování systému, což zajišťuje, že implementace přesně odpovídá navržené specifikaci.}')

# 5. Hierarchie distribucí a model Upstream/Downstream
c = c.replace('\\subsection{Hierarchie distribucí a model Upstream/Downstream}', '\\subsection{\\sout{Hierarchie distribucí a model Upstream/Downstream}}')
c = c.replace('Linuxový ekosystém je charakteristický svou fragmentací, která je však organizována do logických struktur. Základem jsou tzv. foundational distributions (např. Debian, Fedora, Arch Linux, Slackware), ze kterých se odvozují stovky dalších variant.', '\\sout{Linuxový ekosystém je charakteristický svou fragmentací, která je však organizována do logických struktur. Základem jsou tzv. foundational distributions (např. Debian, Fedora, Arch Linux, Slackware), ze kterých se odvozují stovky dalších variant.}')
c = c.replace('Vztah mezi vývojáři a uživateli je definován modelem Upstream/Downstream \\cite{luminousmen_upstream}:', '\\sout{Vztah mezi vývojáři a uživateli je definován modelem Upstream/Downstream }\\cite{luminousmen_upstream}\\sout{:}')
c = c.replace('\\item \\textbf{Upstream (Horní proud):} Představuje autory původního zdrojového kódu (např. projekt Linux kernel, GNOME, nebo samotný vývojář aplikace). Zde probíhá primární vývoj a opravy chyb.', '\\item \\sout{\\textbf{Upstream (Horní proud):} Představuje autory původního zdrojového kódu (např. projekt Linux kernel, GNOME, nebo samotný vývojář aplikace). Zde probíhá primární vývoj a opravy chyb.}')
c = c.replace('\\item \\textbf{Downstream (Dolní proud):} Představuje linuxové distribuce, které přebírají kód z upstreamu, upravují jej pro své potřeby (např. aplikací specifických patchů), kompilují a balí do binárních balíčků.', '\\item \\sout{\\textbf{Downstream (Dolní proud):} Představuje linuxové distribuce, které přebírají kód z upstreamu, upravují jej pro své potřeby (např. aplikací specifických patchů), kompilují a balí do binárních balíčků.}')
c = c.replace('\\begin{figure}[H]\n    \\centering\n    \\includegraphics[width=0.7\\textwidth]{images/upstream-downstream.png}\n    \\caption{Model Upstream a Downstream v distribuci softwaru \\cite{luminousmen_upstream}}\n    \\label{fig:upstream_downstream}\n\\end{figure}', '%\\begin{figure}[H]\n%    \\centering\n%    \\includegraphics[width=0.7\\textwidth]{images/upstream-downstream.png}\n%    \\caption{Model Upstream a Downstream v distribuci softwaru \\cite{luminousmen_upstream}}\n%    \\label{fig:upstream_downstream}\n%\\end{figure}')
c = c.replace('Příkladem hierarchie je rodina Debian: Debian (foundational) $\\rightarrow$ Ubuntu (downstream vůči Debianu) $\\rightarrow$ Linux Mint (downstream vůči Ubuntu). Tato hierarchie umožňuje efektivní sdílení oprav a inovací – oprava v upstreamu postupně „proteče“ všemi downstream distribucemi k uživatelům.', '\\sout{Příkladem hierarchie je rodina Debian: Debian (foundational) }$\\rightarrow$\\sout{ Ubuntu (downstream vůči Debianu) }$\\rightarrow$\\sout{ Linux Mint (downstream vůči Ubuntu). Tato hierarchie umožňuje efektivní sdílení oprav a inovací – oprava v upstreamu postupně „proteče“ všemi downstream distribucemi k uživatelům.}')

# 6. Agilní metodiky a Extreme Programming
c = c.replace('\\section{Agilní metodiky a Extreme Programming}', '\\section{\\sout{Agilní metodiky a Extreme Programming}}')
c = c.replace('Moderní vývoj softwaru se v posledních dvou dekádách posunul od rigidních modelů typu vodopádový model (Waterfall) k agilním přístupům, které kladou důraz na adaptabilitu a lidský faktor. Jednou z nejvlivnějších metodik v této oblasti je Extreme Programming (XP), kterou definoval Kent Beck na konci 90. let 20. století. XP se zaměřuje na zvyšování kvality softwaru a schopnost týmu reagovat na měnící se požadavky zákazníka skrze intenzivní aplikaci osvědčených inženýrských praktik \\cite{beck_xp}.', '\\sout{Moderní vývoj softwaru se v posledních dvou dekádách posunul od rigidních modelů typu vodopádový model (Waterfall) k agilním přístupům, které kladou důraz na adaptabilitu a lidský faktor. Jednou z nejvlivnějších metodik v této oblasti je Extreme Programming (XP), kterou definoval Kent Beck na konci 90. let 20. století. XP se zaměřuje na zvyšování kvality softwaru a schopnost týmu reagovat na měnící se požadavky zákazníka skrze intenzivní aplikaci osvědčených inženýrských praktik }\\cite{beck_xp}\\sout{.}')
c = c.replace('\\subsection{Filozofie a hodnoty XP}', '\\subsection{\\sout{Filozofie a hodnoty XP}}')
c = c.replace('Základem metodiky XP je pět core hodnot, které tvoří etický a profesní rámec pro veškeré rozhodování v projektu \\cite{beck_xp}:', '\\sout{Základem metodiky XP je pět core hodnot, které tvoří etický a profesní rámec pro veškeré rozhodování v projektu }\\cite{beck_xp}\\sout{:}')
c = c.replace('\\item \\textbf{Komunikace (Communication):} Většina problémů v projektech pramení z nedostatku informací. XP podporuje přímou a otevřenou komunikaci mezi členy týmu i zákazníkem.', '\\item \\sout{\\textbf{Komunikace (Communication):} Většina problémů v projektech pramení z nedostatku informací. XP podporuje přímou a otevřenou komunikaci mezi členy týmu i zákazníkem.}')
c = c.replace('\\item \\textbf{Jednoduchost (Simplicity):} Cílem je vytvořit „nejjednodušší věc, která může fungovat“. Tím se minimalizuje budoucí režie a technický dluh.', '\\item \\sout{\\textbf{Jednoduchost (Simplicity):} Cílem je vytvořit „nejjednodušší věc, která může fungovat“. Tím se minimalizuje budoucí režie a technický dluh.}')
c = c.replace('\\item \\textbf{Zpětná vazba (Feedback):} Neustálé ověřování stavu systému skrze testy a interakci se zákazníkem umožňuje včasnou korekci kurzu.', '\\item \\sout{\\textbf{Zpětná vazba (Feedback):} Neustálé ověřování stavu systému skrze testy a interakci se zákazníkem umožňuje včasnou korekci kurzu.}')
c = c.replace('\\item \\textbf{Odvaha (Courage):} Schopnost provádět radikální změny v návrhu (refactoring) nebo přiznat chybu a zahodit nefunkční kód.', '\\item \\sout{\\textbf{Odvaha (Courage):} Schopnost provádět radikální změny v návrhu (refactoring) nebo přiznat chybu a zahodit nefunkční kód.}')
c = c.replace('\\item \\textbf{Respekt (Respect):} Vzájemná úcta mezi vývojáři a důvěra v jejich schopnosti jsou nezbytné pro fungování týmových praktik.', '\\item \\sout{\\textbf{Respekt (Respect):} Vzájemná úcta mezi vývojáři a důvěra v jejich schopnosti jsou nezbytné pro fungování týmových praktik.}')
c = c.replace('\\subsection{Klíčové praktiky XP}', '\\subsection{\\sout{Klíčové praktiky XP}}')
c = c.replace('Hodnoty jsou v XP přetaveny do konkrétních technických a procesních praktik \\cite{beck_xp}. Pro tuto bakalářskou práci byly klíčové zejména:', '\\sout{Hodnoty jsou v XP přetaveny do konkrétních technických a procesních praktik }\\cite{beck_xp}\\sout{. Pro tuto bakalářskou práci byly klíčové zejména:}')
c = c.replace('\\item \\textbf{Test-Driven Development (TDD):} Psaní testů před samotným kódem zajišťuje vysoké pokrytí, definuje očekávané chování a slouží jako pojistka při refactoringu.', '\\item \\sout{\\textbf{Test-Driven Development (TDD):} Psaní testů před samotným kódem zajišťuje vysoké pokrytí, definuje očekávané chování a slouží jako pojistka při refactoringu.}')
c = c.replace('\\item \\textbf{Kontinuální integrace (Continuous Integration - CI):} Časté začleňování změn do hlavní větve projektu a automatické spouštění testů pro okamžitou detekci regresí.', '\\item \\sout{\\textbf{Kontinuální integrace (Continuous Integration - CI):} Časté začleňování změn do hlavní větve projektu a automatické spouštění testů pro okamžitou detekci regresí.}')
c = c.replace('\\item \\textbf{Refactoring:} Neustálé vylepšování vnitřní struktury kódu bez změny jeho vnějšího chování s cílem zachovat čistotu a udržitelnost designu.', '\\item \\sout{\\textbf{Refactoring:} Neustálé vylepšování vnitřní struktury kódu bez změny jeho vnějšího chování s cílem zachovat čistotu a udržitelnost designu.}')
c = c.replace('\\item \\textbf{Jednoduchý návrh (Simple Design):} Návrh systému odpovídá pouze aktuálním požadavkům, čímž se předchází nadměrné komplexitě (over-engineering).', '\\item \\sout{\\textbf{Jednoduchý návrh (Simple Design):} Návrh systému odpovídá pouze aktuálním požadavkům, čímž se předchází nadměrné komplexitě (over-engineering).}')
c = c.replace('\\item \\textbf{Párové programování (Pair Programming):} Praktika, kdy dva vývojáři pracují na jednom úkolu u jednoho počítače, což zvyšuje kvalitu kódu skrze okamžité code review.', '\\item \\sout{\\textbf{Párové programování (Pair Programming):} Praktika, kdy dva vývojáři pracují na jednom úkolu u jednoho počítače, což zvyšuje kvalitu kódu skrze okamžité code review.}')
c = c.replace('Zatímco metodika XP je primárně navržena pro týmovou spolupráci (zejména párové programování), její technické praktiky jako TDD, CI a Refactoring jsou plně aplikovatelné i pro samostatně pracujícího vývojáře a byly pro tuto bakalářskou práci klíčové.', '\\sout{Zatímco metodika XP je primárně navržena pro týmovou spolupráci (zejména párové programování), její technické praktiky jako TDD, CI a Refactoring jsou plně aplikovatelné i pro samostatně pracujícího vývojáře a byly pro tuto bakalářskou práci klíčové.}')

with open(path, 'w', encoding='utf-8') as f:
    f.write(c)

