package model

import (
	"ga-cli/internal/ipc"
)

// GetAppState retrieves the current status of the application
// from the background service via IPC.
func GetAppState(client ipc.Client) (*AppStateResponse, error) {
	resp, err := client.Send("check_state", nil)
	if err != nil {
		return nil, err
	}

	return ipc.Unpack[AppStateResponse](resp)
}

// Internal structures used for state management
// and communication between the frontend and backend.
//
// These structures are kept synchronized with the
// .NET implementation to ensure seamless deserialization.
//
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...

// AppStateResponse represents the unified state of the application
// returned by the background service.
type AppStateResponse struct {
	IsLoggedIn             bool   `json:"isLoggedIn"`
	IsConnected            bool   `json:"isConnected"`
	UserName               string `json:"userName"`
	IsAnotherUserConnected bool   `json:"isAnotherUserConnected"`
	
	// UpdateAvailable is set to true if the service detects 
	// a newer version on the central API.
	UpdateAvailable        bool   `json:"updateAvailable"`
}
